# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20160414_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='spotify_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
