# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20160414_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='spotify_id',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
