# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_auto_20160803_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='follows',
        ),
    ]
